export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const SAVE_ID = 'SAVE_ID';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_MAPPED_CATEGORIES = 'GET_MAPPED_CATEGORIES';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const GET_INVENTORY = 'GET_INVENTORY';
export const DECREASE_INVENTORY = 'DECREASE_INVENTORY';
export const INCREASE_INVENTORY = 'INCREASE_INVENTORY';
export const GET_ITEM = 'GET_ITEM';

export const SET_LOADING = 'SET_LOADING';

export const SELECT_TABLE = 'SELECT_TABLE';
export const SELECT_ITEM_ORDER = 'SELECT_ITEM_ORDER';
export const ADD_ITEM_ORDER = 'ADD_ITEM_ORDER';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const RESET_ORDER = 'RESET_ORDER';
export const SAVE_ORDER = 'SAVE_ORDER';
